load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load(":layer.bzl", "factorio_layer")
load(":repos.bzl", "VERSION_factorio")

# config-path.cfg configures the following:
# - `config-path` is `/etc/factorio`
# - `write-data` is `~/.factorio` (via use-system-read-write-data-directories=true)
# - `read-data` is `/usr/share/factorio` (via use-system-read-write-data-directories=true)
#

factorio_layer(
    name = "factorio_headless",
    config = "config-path.cfg",
    bin_srcs = ["@factorio_headless_release//:bin"],
    data_srcs = ["@factorio_headless_release//:data"],
    out = "factorio_headless.tar",
)

oci_image(
    name = "image",
    base = "@distroless_base",
    entrypoint = ["/opt/factorio/bin/x64/factorio"],
    tars = [
        ":factorio_headless",
    ],
)

oci_load(
    name = "image_tarball",
    image = ":image",
    repo_tags = ["factorio-server:bazel"],
)

oci_push(
    name = "image_push",
    image = ":image",
    remote_tags = [
        "latest",
        "factorio-{}".format(VERSION_factorio),
    ],
    repository = "ghcr.io/lanofdoom/factorio-server",
)

sh_test(
    name = "test_create_map",
    srcs = ["test_create_map.sh"],
    args = [
        "$(location :image_tarball)",
        "test.zip",
    ],
    data = [":image_tarball"],
    deps = ["@bazel_tools//tools/bash/runfiles"],
)
