module(name = "factorio_server")

bazel_dep(name = "rules_oci", version = "2.3.0")
oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "distroless_base",
    digest = "sha256:ed7c407fd64eb0af9dddb9456b94cee188a40a7f53cf38c9836e1e9ae14fca02",
    image = "gcr.io/distroless/cc",
    platforms = ["linux/amd64"],
)
use_repo(oci, "distroless_base", "distroless_base_linux_amd64")

bazel_dep(name = "rules_pkg", version = "1.3.0")

repos = use_extension("//:repos.bzl", "repos_bzlmod")
use_repo(
    repos,
    "factorio_headless_release",
)
