name: renovate
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  renovate:
    name: renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "${{ secrets.RENOVATE_APP_ID }}"
          private-key: "${{ secrets.RENOVATE_APP_PRIVATE_KEY }}"
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v41.0.20
        with:
          token: "${{ steps.app-token.outputs.token }}"
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: "debug"
          RENOVATE_ALLOWED_COMMANDS: "bazelisk mod deps"
